name: fds_flutter_app
description: FDS Bengali PDF Statement System Flutter App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  intl: ^0.18.1
  pdf: ^3.10.4
  printing: ^5.11.0
  flutter_pdfview: ^1.3.2
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/